#!/bin/bash                                                                                                                                                             
sensors | grep "Core 1" | awk '{print $3}' | tr -d +°
