#!/usr/bin/env python
import sys
import re
import urllib
import os

if __name__ == '__main__':
	if len(sys.argv) < 2:
		print 'no argument!'
		sys.exit(1)

	arg = sys.argv[1]
	numexp = re.compile('http://www.mininova.org/tor/(\d*)')
	num = numexp.match(arg).group(1)
	url = 'http://www.mininova.org/get/' + num
	(filename, headers) = urllib.urlretrieve(url)
	nameexp = re.compile('inline; filename="(.*)"')
	name = nameexp.match(headers.dict['content-disposition']).group(1)
	os.rename(filename, name)
	print 'Done', name

