#!/bin/bash

# No trailing slash
PODCAST=~/Podcast
MUSIC=~/Music
PATH=$PATH:~/bin
CODING=mp3 # or ogg
# Get the podcasts
/usr/bin/podget -s

mkdir -p $MUSIC/Podcast
cd $PODCAST

case "$1" in
    -c)
	name=$(basename "$2" .m4a)
	source="$PODCAST/$2"
	product="$MUSIC/Podcast/$name.$CODING"
	tmp="/tmp/$name.wav"
	if [ ! -f $product ]
	then
	    echo "new download $product"
	    case "$CODING" in
		mp3)
		    nice mplayer -really-quiet "$source" -ao pcm:file="$tmp" && lame -Srh "$tmp" "$product" ; rm "$tmp" &
		    ;;
		ogg)
		    nice mplayer -really-quiet "$source" -ao pcm:file="$tmp" && nice oggenc -Q -q5 "$tmp"  -o "$product" ; rm "$tmp" &
		    ;;
	    esac
	fi
	;;
    *)
	find . -name "*.m4a" -type f -exec mypodget -c '{}' \& \;
	;;
esac
